### PR TITLE
Added binary support

### PR DESCRIPTION
**Pull request by feus4177**
I tried to be thorough while at the same time not making any large architectural changes. Let me know what you think. I can go back and make changes if you have any major concerns.

### CODE REVIEW

**Comment by invisibleroads** [comment]
Wow, thanks! I'll take a look over the weekend.

**Comment by feus4177** [comment]
Alright I've fixed the support for python versions 2.6/3.4. If you can get it merged in and published I would really appreciate it.

**Comment by feus4177** [comment]
Any idea when this might get merged?

**Comment by softforge** [comment]
It would be great to get this merged. We're soon going to need binary support so can do some testing...

**Comment by EnGassa** [comment]
Hi @invisibleroads, is there a plan to merge this request? We have been waiting for this for a while.

**Comment by feus4177** [comment]
For those of you still interested I went ahead and released my version of the package.

**Comment by stafyniaksacha** [comment]
Hello @feus4177, 
If you want I'll will maintain this project into a forked repo here : https://github.com/stafyniaksacha/socketIO-client
Can you make a pull request here ?

**Comment by feus4177** [comment]
I was actually just recently forked the project and am maintaining it here
<https://github.com/feus4177/socketIO-client-2/>.

On Sat, Mar 5, 2016 at 3:56 AM, Sacha STAFYNIAK <notifications@github.com>
wrote:

> Hello @feus4177 <https://github.com/feus4177>,
> If you want I'll will maintain this project into a forked repo here :
> https://github.com/stafyniaksacha/socketIO-client
> Can you make a pull request here ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/invisibleroads/socketIO-client/pull/85#issuecomment-192626678>
> .
>



-- 
*John Feusi*
*CTO*
*Element Robot LLC*
*(208) 863-0849*
*jf@elementrobot.com <jf@elementrobot.com>*

**Comment by invisibleroads** [comment]
Thanks to @feus4177 for maintaining support for binary events and acks; for now, if you need binary support, you can use the version by @feus4177.

I tried to work through the pull request this week, but ran out of brainpower.

I'll revisit this issue once I have a chance to test the binary protocol firsthand.

**Comment by oeway** [comment]
Hi, is there any chance that this got merged? Thanks.

**Pull request closed without merging**
