### PR TITLE
 Add Debian packaging support

### PR DESCRIPTION
**Pull request by adamwight**
Thanks for writing this library!  Please let me know if you'd rather put this Debian metadata in a separate branch, or another repo, even.

TODO:
* RHH should sign off, cos I've made assumptions and pasted his name everywhere
as the maintainer.
* Tests are not passing, so I disabled for now.
* Haven't tested the backport to the master branch.

### CODE REVIEW

**Comment by invisibleroads** [comment]
Thanks, this is an interesting development, but why version 0.5.6? Is the use of socket.io protocol 0.9 more widespread than protocol 1.x?

Would it make sense then to attempt to integrate support for both protocol 0.9 and 1.x into a single client?

**Comment by adamwight** [comment]
Hi, thanks for taking a look!  I don't know about adoption in general, but in our case we're connecting to an existing service which uses the 0.9 protocol, a [recent changes](https://wikitech.wikimedia.org/wiki/RCStream) feed for Wikimedia projects.  I see some [discussion](https://phabricator.wikimedia.org/T68232) which concludes that the server will be upgraded to use the new protocol when a Debian package exists for python-(gevent-)socketio that supports 1.0.

Unfortunately, that project is [not planning](https://github.com/abourget/gevent-socketio/issues/192) socketio 1.0 integration, however there is an [independent rewrite](https://github.com/shuoli84/gevent_socketio2) in progress which might fill the gap.  This indicates that Python projects are probably locked into 0.9 for the near future, although I expect that nodejs projects have fully embraces 1.0.

In the meantime, we're happy to use the old version of your library, but I see how it would be logistically annoying to support packages built from multiple versions.  They would have to have different names, to start with...  I'm sure this patch will apply to master as well, I was hoping to port it with your agreement.

How difficult do you expect it would be to support both protocols in the newer code?  Less annoying than dealing with split version packaging?

**Comment by adamwight** [comment]
This slightly changes things on our end--I was just informed that the plan is to rewrite our server in nodejs so that it uses the 1.0 protocol.

My thinking is currently that it would be fine to merge the debian packaging on the master branch, and we'll just roll a 0.5.6 package in private until we're ready to upgrade...

**Comment by adamwight** [comment]
Switching to branch debian_packaging_0_6...

**Pull request closed without merging**
