### PR TITLE
Socketio.v1 compat

### PR DESCRIPTION
**Pull request by sarietta**
I have updated the python client to be compatible with the newest version of Socket.IO server. This included a lot of changes to the core of the code to make the client work with the newer protocols.

All of the unit tests from the previous release are passing.

### CODE REVIEW

**Comment by invisibleroads** [comment]
Hi Sean, the start-test-server and kill-test-server scripts seem to be missing.

**Comment by invisibleroads** [comment]
Also, how memory-hungry are multiprocessing threads?  I remember there were some users who wanted to run the library on raspberry pi type hardware, so I switched out heartbeat threads in favor of coroutines, which did lead to dramatic memory savings.

**Comment by invisibleroads** [comment]
There is an interesting article on multiprocessing memory usage here.
http://stackoverflow.com/questions/14749897/python-multiprocessing-memory-usage

**Comment by invisibleroads** [comment]
I think for now, once you include the bash scripts for starting and killing the server, I'll make sure the tests work, merge your pull request and work off of that version.

**Comment by sarietta** [comment]
I have included the scripts. Please see my comment in #52 re: memory footprint issues.

**Pull request merged**
